name: CI/CD Pipeline - Confluence Upload

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Enter Docker image tag (e.g., v1.0.0 or latest)"
        required: true
        default: "latest"

jobs:
  build-release-assets:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [win-x64, linux-x64, osx-x64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Build for ${{ matrix.platform }}
        run: dotnet publish -c Release -r ${{ matrix.platform }} --self-contained -o ./publish/${{ matrix.platform }}

      - name: Zip binaries
        run: |
          cd ./publish/${{ matrix.platform }}
          zip -r ../${{ matrix.platform }}.zip .
          cd ../..

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}
          path: ./publish/${{ matrix.platform }}.zip

  upload-to-confluence:
    runs-on: ubuntu-latest
    needs: build-release-assets
    environment: QA  # Ensure secrets come from QA
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Upload Windows zip to Confluence
        run: |
          curl -u "${{ secrets.CONFLUENCE_EMAIL }}:${{ secrets.CONFLUENCE_TOKEN }}" \
               -X POST \
               -H "X-Atlassian-Token: no-check" \
               -F "file=@./artifacts/win-x64/win-x64.zip" \
               "${{ secrets.CONFLUENCE_BASE_URL }}/rest/api/content/${{ secrets.CONFLUENCE_PAGE_ID }}/child/attachment"

      - name: Upload Linux zip to Confluence
        run: |
          curl -u "${{ secrets.CONFLUENCE_EMAIL }}:${{ secrets.CONFLUENCE_TOKEN }}" \
               -X POST \
               -H "X-Atlassian-Token: no-check" \
               -F "file=@./artifacts/linux-x64/linux-x64.zip" \
               "${{ secrets.CONFLUENCE_BASE_URL }}/rest/api/content/${{ secrets.CONFLUENCE_PAGE_ID }}/child/attachment"

      - name: Upload macOS zip to Confluence
        run: |
          curl -u "${{ secrets.CONFLUENCE_EMAIL }}:${{ secrets.CONFLUENCE_TOKEN }}" \
               -X POST \
               -H "X-Atlassian-Token: no-check" \
               -F "file=@./artifacts/osx-x64/osx-x64.zip" \
               "${{ secrets.CONFLUENCE_BASE_URL }}/rest/api/content/${{ secrets.CONFLUENCE_PAGE_ID }}/child/attachment"