name: CI/CD Pipeline

on:
  push:
    tags:
      - 'v*'  # Trigger on tags like v1.0.0, v2.0.0, etc.
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: QA  # Specify the environment (e.g., QA)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'  # Adjust to your target .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Pack the project
        run: dotnet pack --configuration Release --output ./nupkgs

      - name: Publish to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}  # Reference the secret from the QA environment
        run: dotnet nuget push ./nupkgs/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json

  build-release-assets:
    runs-on: ubuntu-latest
    needs: build-and-publish  # Wait for the build-and-publish job to complete
    strategy:
      matrix:
        platform: [win-x64, linux-x64, osx-x64]  # Target platforms
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Build for ${{ matrix.platform }}
        run: dotnet publish -c Release -r ${{ matrix.platform }} -o ./publish/${{ matrix.platform }}

      - name: Zip binaries
        run: |
          cd ./publish/${{ matrix.platform }}
          zip -r ../${{ matrix.platform }}.zip .
          cd ../..

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}
          path: ./publish/${{ matrix.platform }}.zip

  create-release:
    runs-on: ubuntu-latest
    needs: build-release-assets  # Wait for the build-release-assets job to complete
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag_name || github.ref_name }}  # Use input or tag name
          release_name: Release ${{ github.event.inputs.tag_name || github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/win-x64/win-x64.zip
          asset_name: win-x64.zip
          asset_content_type: application/zip

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/linux-x64/linux-x64.zip
          asset_name: linux-x64.zip
          asset_content_type: application/zip

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/osx-x64/osx-x64.zip
          asset_name: osx-x64.zip
          asset_content_type: application/zip

  update-homebrew-formula:
    runs-on: ubuntu-latest
    needs: create-release  # Wait for the create-release job to complete
    steps:
      - name: Checkout homebrew-demoCLI
        uses: actions/checkout@v3s
        with:
          repository: Vineet-Fullstack/homebrew-demoCLI
          path: homebrew-demoCLI

      - name: Get release info
        id: get_release
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          echo "URL=https://github.com/${{ github.repository }}/releases/download/v${{ env.VERSION }}/osx-x64.zip" >> $GITHUB_ENV
          echo "SHA256=$(curl -sL ${{ env.URL }} | shasum -a 256 | awk '{print $1}')" >> $GITHUB_ENV

      - name: Update formula
        run: |
          sed -i "s|url .*|url \"${{ env.URL }}\"|" homebrew-demoCLI/Formula/demoCLI.rb
          sed -i "s|sha256 .*|sha256 \"${{ env.SHA256 }}\"|" homebrew-demoCLI/Formula/demoCLI.rb
          sed -i "s|version .*|version \"${{ env.VERSION }}\"|" homebrew-demoCLI/Formula/demoCLI.rb

      - name: Commit and push changes
        run: |
          cd homebrew-demoCLI
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add Formula/demoCLI.rb
          git commit -m "Update demoCLI to ${{ env.VERSION }}"
          git pushs