name: CI/CD Pipeline

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0, v2.0.0, etc.

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: QA  # Ensure secrets come from QA
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Pack the project
        run: dotnet pack --configuration Release --output ./nupkgs

      # Publish to NuGet.org
      - name: Publish to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push ./nupkgs/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json

      # Authenticate and Publish to GitHub Packages
      - name: Add GitHub Packages Source
        run: |
          dotnet nuget add source "https://nuget.pkg.github.com/Vineet-Fullstack/index.json" \
            --name "github" \
            --username ${{ github.actor }} \
            --password ${{ secrets.PAT_TOKEN }} \
            --store-password-in-clear-text

      - name: Publish to GitHub Packages
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: dotnet nuget push ./nupkgs/*.nupkg --api-key $PAT_TOKEN --source "https://nuget.pkg.github.com/Vineet-Fullstack/index.json"


  build-release-assets:
    runs-on: ubuntu-latest
    needs: build-and-publish
    strategy:
      matrix:
        platform: [win-x64, linux-x64, osx-x64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Build for ${{ matrix.platform }}
        run: dotnet publish -c Release -r ${{ matrix.platform }} -o ./publish/${{ matrix.platform }}

      - name: Zip binaries
        run: |
          cd ./publish/${{ matrix.platform }}
          zip -r ../${{ matrix.platform }}.zip .
          cd ../..

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}
          path: ./publish/${{ matrix.platform }}.zip

  create-release:
    runs-on: ubuntu-latest
    needs: build-release-assets
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Assets (Windows)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/win-x64/win-x64.zip
          asset_name: win-x64.zip
          asset_content_type: application/zip

      - name: Upload Release Assets (Linux)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/linux-x64/linux-x64.zip
          asset_name: linux-x64.zip
          asset_content_type: application/zip

      - name: Upload Release Assets (macOS)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/osx-x64/osx-x64.zip
          asset_name: osx-x64.zip
          asset_content_type: application/zip

  update-homebrew-formula:
    runs-on: ubuntu-latest
    needs: create-release
    environment: QA  # Ensure secrets come from QA
    steps:
      - name: Checkout homebrew-demoCLI repository
        uses: actions/checkout@v3
        with:
          repository: Vineet-Fullstack/homebrew-demoCLI
          path: homebrew-demoCLI
          token: ${{ secrets.PAT_TOKEN }}  # Ensure authentication

      - name: Get the latest release version from demoCLI repository
        id: get_release
        run: |
          VERSION=$(curl -s "https://api.github.com/repos/Vineet-Fullstack/demoCLI/releases/latest" | jq -r .tag_name)
          DOWNLOAD_URL="https://github.com/Vineet-Fullstack/demoCLI/releases/download/${VERSION}/osx-x64.zip"
          SHA256=$(curl -sL ${DOWNLOAD_URL} | shasum -a 256 | awk '{print $1}')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "URL=${DOWNLOAD_URL}" >> $GITHUB_ENV
          echo "SHA256=${SHA256}" >> $GITHUB_ENV

      - name: Debug - Print the fetched values
        run: |
          echo "Version: ${{ env.VERSION }}"
          echo "URL: ${{ env.URL }}"
          echo "SHA256: ${{ env.SHA256 }}"

      - name: Update Homebrew formula (demoCLI.rb)
        run: |
          sed -i "s|url .*|url \"${{ env.URL }}\"|" homebrew-demoCLI/Formula/democli.rb
          sed -i "s|sha256 .*|sha256 \"${{ env.SHA256 }}\"|" homebrew-demoCLI/Formula/democli.rb
          sed -i "s|version .*|version \"${{ env.VERSION }}\"|" homebrew-demoCLI/Formula/democli.rb

      - name: Commit and push changes
        run: |
          cd homebrew-demoCLI
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add Formula/democli.rb
          git commit -m "Update demoCLI to ${{ env.VERSION }}"
          git push origin main
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
