name: Publish on Confluence page

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0, v2.0.0, etc.

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      environment: deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

  build-release-assets:
    runs-on: ubuntu-latest
    needs: build-and-publish
    strategy:
      matrix:
        platform: [win-x64, linux-x64, osx-x64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Build for ${{ matrix.platform }}
        run: dotnet publish -c Release -r ${{ matrix.platform }} --self-contained -o ./publish/${{ matrix.platform }}

      - name: Zip binaries
        run: |
          cd ./publish/${{ matrix.platform }}
          zip -r ../${{ matrix.platform }}.zip .
          cd ../..

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}
          path: ./publish/${{ matrix.platform }}.zip

  upload-to-confluence:
    runs-on: ubuntu-latest
    needs: build-release-assets
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Upload Windows zip to Confluence
        run: |
          curl -u "${{ secrets.CONFLUENCE_EMAIL }}:${{ secrets.CONFLUENCE_TOKEN }}" \
               -X POST \
               -H "X-Atlassian-Token: no-check" \
               -F "file=@./artifacts/win-x64/win-x64.zip" \
               "${{ secrets.CONFLUENCE_BASE_URL }}/rest/api/content/${{ secrets.CONFLUENCE_PAGE_ID }}/child/attachment"

      - name: Upload Linux zip to Confluence
        run: |
          curl -u "${{ secrets.CONFLUENCE_EMAIL }}:${{ secrets.CONFLUENCE_TOKEN }}" \
               -X POST \
               -H "X-Atlassian-Token: no-check" \
               -F "file=@./artifacts/linux-x64/linux-x64.zip" \
               "${{ secrets.CONFLUENCE_BASE_URL }}/rest/api/content/${{ secrets.CONFLUENCE_PAGE_ID }}/child/attachment"

      - name: Upload macOS zip to Confluence
        run: |
          curl -u "${{ secrets.CONFLUENCE_EMAIL }}:${{ secrets.CONFLUENCE_TOKEN }}" \
               -X POST \
               -H "X-Atlassian-Token: no-check" \
               -F "file=@./artifacts/osx-x64/osx-x64.zip" \
               "${{ secrets.CONFLUENCE_BASE_URL }}/rest/api/content/${{ secrets.CONFLUENCE_PAGE_ID }}/child/attachment"