name: Deploy DocFX Documentation to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Ensure this is the version you are using

      - name: Install DocFX
        run: |
          dotnet tool install --global docfx

      - name: Build DocFX documentation
        run: |
          docfx build ./DocFX/docfx.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          folder: './_site'  # Folder where DocFX generates the documentation
          target_branch: gh-pages  # GitHub Pages branch
          github_token: ${{ secrets.GITHUB_TOKEN }}
