name: Publish Docker Image

on:
  workflow_dispatch:  # Allow manual triggering
    inputs:
      docker_tag:
        description: 'Docker image tag (e.g., 1.0, latest)'
        required: true
        default: 'latest'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    environment: QA
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/demo-cli:${{ github.event.inputs.docker_tag }}