name: Publish Docker Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Enter Docker image tag (e.g., v1.0.0 or latest)"
        required: true
        default: "latest"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: QA

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/democli:${{ github.event.inputs.tag }} .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/democli:${{ github.event.inputs.tag }} ${{ secrets.DOCKERHUB_USERNAME }}/democli:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/democli:${{ github.event.inputs.tag }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/democli:latest