name: Build and Release CLI Tool

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release version (e.g., 1.0.0)"
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [win-x64, linux-x64, osx-x64] # Platforms to target
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish self-contained binary
        run: |
          dotnet publish -c Release -r ${{ matrix.os }} --self-contained true /p:PublishSingleFile=true /p:IncludeAllContentForSelfExtract=true
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1

      - name: Archive binary
        run: |
          zip -j "${{ matrix.os }}-demoCLI.zip" bin/Release/net8.0/${{ matrix.os }}/*
        if: runner.os == 'Windows'

      - name: Upload release assets
        uses: actions/upload-release-asset@v3
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_id: ${{ steps.create_release.outputs.id }}
          asset_path: ./${{ matrix.os }}-demoCLI.zip
          asset_name: demoCLI-${{ matrix.os }}.zip
          content_type: application/zip
