name: Build and Release CLI Tool

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release version (e.g., 1.0.0)"
        required: true

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      # Step 3: Publish binaries for Windows, macOS, and Linux
      - name: Publish Windows Binary
        run: dotnet publish -c Release -r win-x64 --self-contained true -o publish/windows

      - name: Publish macOS Binary
        run: dotnet publish -c Release -r osx-x64 --self-contained true -o publish/macos

      - name: Publish Linux Binary
        run: dotnet publish -c Release -r linux-x64 --self-contained true -o publish/linux

      # Step 4: Create a GitHub Release and upload binaries
      - name: Create Release and Upload Binaries
        uses: softprops/action-gh-release@v2
        with:
          name: "Release ${{ github.event.inputs.release_version }}"
          tag_name: ${{ github.event.inputs.release_version }}  # Use version input directly for the release name and tag
          files: |
            publish/windows/*
            publish/macos/*
            publish/linux/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub's default token for the release upload
